name: controller_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

dependencies:
  fluent_ui: ^4.8.5
  fluentui_system_icons: ^1.1.225
  flutter:
    sdk: flutter
  provider: ^6.1.1
  win32_gamepad: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
